version: 2.0

references:

  workspace_root: &workspace_root
      ~/code

  container_config: &container_config
    docker:
      - image: circleci/android:api-28

    working_directory: *workspace_root

    environment:
#      TERM: dumb
      JVM_OPTS: -XX\:MaxHeapSize\=2048m -Xmx1536m
      LIBS: NoFree
      BUILD_TYPE: Release
      APPCENTER_OWNER: nicidienase
      APPCENTER_GROUP: "Collaborators"
      RELEASENOTES_FILE: "release_notes.txt"

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  general_cache_key: &general_cache_key
      key: app-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "touch/build.gradle" }}-{{ checksum "leanback/build.gradle" }}-{{ checksum "common/build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:

  build:
    <<: *container_config
    steps:
      - checkout

      - restore_cache:
          <<: *general_cache_key
      - run:
          name: Setup environment
          command: |
            .circleci/setup_env.sh >> $BASH_ENV
            echo "VERSION_CODE_TOUCH=$(.circleci/getVersionCode.sh -t)" >> $BASH_ENV
            echo "VERSION_CODE_LEANBACK=$(.circleci/getVersionCode.sh -l)" >> $BASH_ENV

      - run:
          name: Download Dependencies
          command: |
            ./gradlew $KEY_CONFIG $SIGN_CONFIG \
              -PversionCode=$VERSION_CODE_TOUCH \
              -PversionName=${VERSION_NAME} \
              androidDependencies

      - run:
          name: Build Touch
          command: |
            ./gradlew $SIGN_CONFIG $KEY_CONFIG \
              -PversionCode=$VERSION_CODE_TOUCH \
              -PversionName=${VERSION_NAME} \
              touch:assemble${STAGE_LOWER}${LIBS}${BUILD_TYPE}
      - store_artifacts:
          path: touch/build/outputs
          destination: touch

      - run:
          name: Build Leanback
          command: |
            ./gradlew $KEY_CONFIG $SIGN_CONFIG \
              -PversionCode=$VERSION_CODE_LEANBACK \
              -PversionName=${VERSION_NAME} \
            leanback:assemble${STAGE_LOWER}${LIBS}${BUILD_TYPE}
      - store_artifacts:
          path: leanback/build/outputs
          destination: leanback

      - save_cache:
          <<: *general_cache_key
          paths:
            - "~/.gradle"
            - "~/.m2"
            - "/opt/android-sdk-linux/licenses/"

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  check:
    <<: *container_config
    steps:
      - *attach_workspace

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Setup environment
          command: |
            .circleci/setup_env.sh >> $BASH_ENV
            echo "VERSION_CODE_TOUCH=$(.circleci/getVersionCode.sh -t)" >> $BASH_ENV
            echo "VERSION_CODE_LEANBACK=$(.circleci/getVersionCode.sh -l)" >> $BASH_ENV

      - run:
          name: Run checks
          command: |
            ./gradlew $KEY_CONFIG \
              -PversionCode=$VERSION_CODE_LEANBACK \
              -PversionName=${VERSION_NAME} \
              lint ktlintCheck

      - store_artifacts:
          path: app/build/reports/
          destination: lint_reports/app/

  test:
    <<: *container_config
    steps:
      - *attach_workspace

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Setup environment
          command: |
            .circleci/setup_env.sh >> $BASH_ENV
            echo "VERSION_CODE_TOUCH=$(.circleci/getVersionCode.sh -t)" >> $BASH_ENV
            echo "VERSION_CODE_LEANBACK=$(.circleci/getVersionCode.sh -l)" >> $BASH_ENV

      - run:
          name: Env
          command: cat $BASH_ENV

      - run:
          name: Test Common
          command: |
            ./gradlew $KEY_CONFIG common:test${STAGE}${LIBS}${BUILD_TYPE}UnitTest

      - run:
          name: Test Touch
          command: |
            ./gradlew $KEY_CONFIG \
              -PversionCode=$VERSION_CODE_TOUCH \
              -PversionName=${VERSION_NAME} \
              touch:test${STAGE}${LIBS}${BUILD_TYPE}UnitTest

      - run:
          name: Test Leanback
          command: |
            ./gradlew $KEY_CONFIG \
              -PversionCode=$VERSION_CODE_LEANBACK \
              -PversionName=${VERSION_NAME} \
              leanback:test${STAGE}${LIBS}${BUILD_TYPE}UnitTest \

      - store_artifacts:
          path: touch/build/reports
          destination: touch-reports
      - store_artifacts:
          path: leanback/build/reports
          destination: leanback-reports
      - store_artifacts:
          path: leanback/build/reports
          destination: leanback-reports
      - store_test_results:
          path: common/build/test-results
      - store_test_results:
          path: touch/build/test-results
      - store_test_results:
          path: leanback/build/test-results

  publish:
    <<: *container_config
    steps:
      - *attach_workspace

      - restore_cache:
          <<: *general_cache_key

      - run:
          name: Setup environment
          command: .circleci/setup_env.sh >> $BASH_ENV

      - run:
          name: Touch Appcenter Upload
          branches:
            only:
              - master
              - develop
          command: |
            git log --format="%h %s" master..HEAD > $RELEASENOTES_FILE
            .circleci/appCenterUpload.sh \
              $APPCENTER_OWNER \
              $APPCENTER_TOKEN \
              "touch/build/outputs/apk/${STAGE_LOWER}${LIBS}/${BUILD_TYPE_LOWER}/touch-${STAGE_LOWER}-${LIBS_LOWER}-${BUILD_TYPE_LOWER}.apk" \
              $RELEASENOTES_FILE \
              $APPCENTER_GROUP \
              "touch/build/outputs/mapping/${STAGE_LOWER}${LIBS}/${BUILD_TYPE_LOWER}/mapping.txt" \
              "$VERSION_CODE_TOUCH" \
              "$VERSION_NAME"

      - run:
          name: Leanback Appcenter Upload
          branches:
            only:
              - master
              - develop
          command: |
            git log --format="%h %s" master..HEAD > $RELEASENOTES_FILE
            .circleci/appCenterUpload.sh \
              $APPCENTER_OWNER \
              $APPCENTER_TOKEN \
              "leanback/build/outputs/apk/${STAGE_LOWER}${LIBS}/${BUILD_TYPE_LOWER}/touch-${STAGE_LOWER}-${LIBS_LOWER}-${BUILD_TYPE_LOWER}.apk" \
              $RELEASENOTES_FILE \
              $APPCENTER_GROUP \
              "leanback/build/outputs/mapping/${STAGE_LOWER}${LIBS}/${BUILD_TYPE_LOWER}/mapping.txt" \
              "$VERSION_CODE_LEANBACK" \
              "$VERSION_NAME"

workflows:
  version: 2

  build_test_publish:
    jobs:
      - build
      - check:
          requires:
            - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
            - check
